name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 3 15 * *' # once every per month on the 15th at 03:00 UTC

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run Makefile
        run: make venv dependencies
